export interface IndianCity {
  name: string;
  state: string;
}

export const IndianCitiesData: IndianCity[] = [
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Delhi", state: "Delhi" },
  { name: "Bangalore", state: "Karnataka" },
  { name: "Hyderabad", state: "Telangana" },
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Kolkata", state: "West Bengal" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Surat", state: "Gujarat" },
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Patna", state: "Bihar" },
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Ludhiana", state: "Punjab" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Faridabad", state: "Haryana" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Rajkot", state: "Gujarat" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Aurangabad", state: "Maharashtra" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Amritsar", state: "Punjab" },
  { name: "Navi Mumbai", state: "Maharashtra" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Prayagraj", state: "Uttar Pradesh" },
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Howrah", state: "West Bengal" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Kota", state: "Rajasthan" },
  { name: "Chandigarh", state: "Chandigarh" },
  { name: "Guwahati", state: "Assam" },
  { name: "Solapur", state: "Maharashtra" },
  { name: "Hubli", state: "Karnataka" },
  { name: "Mysore", state: "Karnataka" },
  { name: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Bareilly", state: "Uttar Pradesh" },
  { name: "Aligarh", state: "Uttar Pradesh" },
  { name: "Tiruppur", state: "Tamil Nadu" },
  { name: "Moradabad", state: "Uttar Pradesh" },
  { name: "Jalandhar", state: "Punjab" },
  { name: "Bhubaneswar", state: "Odisha" },
  { name: "Salem", state: "Tamil Nadu" },
  { name: "Warangal", state: "Telangana" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Bhiwandi", state: "Maharashtra" },
  { name: "Saharanpur", state: "Uttar Pradesh" },
  { name: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "Bikaner", state: "Rajasthan" },
  { name: "Amravati", state: "Maharashtra" },
  { name: "Noida", state: "Uttar Pradesh" },
  { name: "Jamshedpur", state: "Jharkhand" },
  { name: "Bhilai", state: "Chhattisgarh" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Firozabad", state: "Uttar Pradesh" },
  { name: "Kochi", state: "Kerala" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Bhavnagar", state: "Gujarat" },
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Durgapur", state: "West Bengal" },
  { name: "Asansol", state: "West Bengal" },
  { name: "Rourkela", state: "Odisha" },
  { name: "Nanded", state: "Maharashtra" },
  { name: "Kolhapur", state: "Maharashtra" },
  { name: "Ajmer", state: "Rajasthan" },
  { name: "Akola", state: "Maharashtra" },
  { name: "Gulbarga", state: "Karnataka" },
  { name: "Jamnagar", state: "Gujarat" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Siliguri", state: "West Bengal" },
  { name: "Jhansi", state: "Uttar Pradesh" },
  { name: "Ulhasnagar", state: "Maharashtra" },
  { name: "Jammu", state: "Jammu and Kashmir" },
  { name: "Sangli", state: "Maharashtra" },
  { name: "Mangalore", state: "Karnataka" },
  { name: "Erode", state: "Tamil Nadu" },
  { name: "Belgaum", state: "Karnataka" },
  { name: "Tirunelveli", state: "Tamil Nadu" },
  { name: "Gaya", state: "Bihar" },
  { name: "Jalgaon", state: "Maharashtra" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Thiruvananthapuram", state: "Kerala" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Kollam", state: "Kerala" },
  { name: "Thrissur", state: "Kerala" },
  { name: "Davanagere", state: "Karnataka" },
  { name: "Bellary", state: "Karnataka" },
  { name: "Shivamogga", state: "Karnataka" },
  { name: "Tumkur", state: "Karnataka" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Rajahmundry", state: "Andhra Pradesh" },
  { name: "Kadapa", state: "Andhra Pradesh" },
  { name: "Kakinada", state: "Andhra Pradesh" },
  { name: "Tirupati", state: "Andhra Pradesh" },
  { name: "Chittoor", state: "Andhra Pradesh" },
  { name: "Anantapur", state: "Andhra Pradesh" },
  { name: "Nizamabad", state: "Telangana" },
  { name: "Khammam", state: "Telangana" },
  { name: "Karimnagar", state: "Telangana" },
  { name: "Bokaro", state: "Jharkhand" },
  { name: "Bhagalpur", state: "Bihar" },
  { name: "Muzaffarpur", state: "Bihar" },
  { name: "Darbhanga", state: "Bihar" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Durg", state: "Chhattisgarh" },
  { name: "Dewas", state: "Madhya Pradesh" },
  { name: "Satna", state: "Madhya Pradesh" },
  { name: "Ratlam", state: "Madhya Pradesh" },
  { name: "Sagar", state: "Madhya Pradesh" },
  { name: "Bharatpur", state: "Rajasthan" },
  { name: "Sikar", state: "Rajasthan" },
  { name: "Bhilwara", state: "Rajasthan" },
  { name: "Alwar", state: "Rajasthan" },
  { name: "Patiala", state: "Punjab" },
  { name: "Bathinda", state: "Punjab" },
  { name: "Rohtak", state: "Haryana" },
  { name: "Panipat", state: "Haryana" },
  { name: "Karnal", state: "Haryana" },
  { name: "Sonipat", state: "Haryana" },
  { name: "Vellore", state: "Tamil Nadu" },
  { name: "Thoothukudi", state: "Tamil Nadu" },
  { name: "Dindigul", state: "Tamil Nadu" },
  { name: "Avadi", state: "Tamil Nadu" },
  { name: "Latur", state: "Maharashtra" },
  { name: "Dhule", state: "Maharashtra" },
  { name: "Ahmednagar", state: "Maharashtra" },
  { name: "Chandrapur", state: "Maharashtra" },
  { name: "Junagadh", state: "Gujarat" },
  { name: "Gandhinagar", state: "Gujarat" },
  { name: "Porbandar", state: "Gujarat" },
  { name: "Bhuj", state: "Gujarat" },
  { name: "Berhampur", state: "Odisha" },
  { name: "Puducherry", state: "Puducherry" },
  { name: "Aizawl", state: "Mizoram" },
  { name: "Imphal", state: "Manipur" },
  { name: "Shillong", state: "Meghalaya" },
  { name: "Silchar", state: "Assam" },
  { name: "Agartala", state: "Tripura" },
  { name: "Gangtok", state: "Sikkim" },
  { name: "New Delhi", state: "Delhi" },
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Port Blair", state: "Andaman and Nicobar Islands" },
];